### ISSUE TITLE
Cannot create a item using a single word as the name

### ISSUE THREAD

**Issue by turbogeek421** [sanifhimani/monday_ruby#16]
# Issue Summary

* `monday.com api` version: `0.6.0`
* Ruby version: `3.1.4`
* Operating system: `x86_64-linux`

When using the `create_item` method, passing a single word string to the `item_name` parameter hash results in a badly formatted mutation with the `item_name` supplied with the string given, but without quotation marks.

## Expected behaviour

Item creation should be possible with a single word string.

## Actual behaviour

An API error response:

```
[{"message"=>"Argument 'item_name' on Field 'create_item' has an invalid value (ItemNameStringGiven). Expected type 'String!'.", "locations"=>[{"line"=>1, "column"=>12}], "path"=>["mutation", "create_item", "item_name"], "extensions"=>{"code"=>"argumentLiteralsIncompatible", "typeName"=>"Field", "argumentName"=>"item_name"}}] (Monday::Error)
```

where the `item_name` string given is 'ItemNameStringGiven'.

## Steps to reproduce

1. Create an item with a single word `item_name`
2. Receive the API error

## Additional context

NA

**Comment by sanifhimani** [comment]
@turbogeek421 This should be fixed with [v0.6.1](https://github.com/sanifhimani/monday_ruby/releases/tag/v0.6.1)
