### ISSUE TITLE
Filter Items by column values

### ISSUE THREAD

**Issue by raviskit** [sanifhimani/monday_ruby#20]
**Is your feature request related to a problem? Please describe.**
I need to fetch items with certain column values. Like if my URL contains this text: "https://google.com" or my email column contains this email: hello@example.com.
I can't even fetch all the items in Monday without providing item ids.

**Describe the solution you'd like**
Here is the API which provides filtering based on column values:
https://developer.monday.com/api-reference/reference/items-page-by-column-values

**Describe alternatives you've considered**
I tried fetching all the items, but Monday returns only 100 items and we have to maintain a cursor for next items.

**Additional context**
This is much needed. I don't want the filtering to be done in ruby. I should be able to pass the arguments and it should return filtered items.

**Comment by sanifhimani** [comment]
Actively working on it - should be released soon
